name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Installation of dependencies
      run: sudo apt update && sudo apt install -y libgtest-dev build-essential cmake gcovr
    
    - name: Build Google Test
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
    
    - name: Compile project
      run: make
    
    - name: Execute tests
      run: ./program.out
