name: C/C++ CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev cmake gcovr
        cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp lib/*.a /usr/lib/
        
    - name: Build and test with coverage
      run: |
        g++ -std=c++17 --coverage -o program.out main.cpp -lgtest -lgtest_main -pthread
        ./program.out --test
        gcovr --xml coverage.xml
        
    - name: Update coverage badge
      uses: schneegans/dynamic-badges-action@v1.0.0
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gistID: ${{ secrets.GIST_ID }}
        filename: coverage.json
        label: coverage
        message: $(grep -o 'line-rate="[0-9.]*"' coverage.xml | head -1 | grep -o '[0-9.]*' | awk '{print int($1*100)"%"}')
        color: green
